name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & test - ${{ matrix.os }} - ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-14", "windows-latest" ]
        python-version: [ "3.12" ]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          pip install pywin32==306

      - name: Install dependencies
        run: |
          pip install ecdsa==0.18.0 sympy==1.11.1

      - name: Build the project (Windows)
        if: runner.os == 'Windows'
        run: |
          powershell.exe ./build_extension.ps1

      - name: Build the project (Unix)
        if: runner.os != 'Windows'
        run: |
          export CMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          ./build_extension.sh

      - name: Run tests
        run: |
          python -m unittest discover
